#include "Bot.hpp"

std::string ft::Bot::jokes[i] = {
		"Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
		"Why was the JavaScript developer sad? Because he didn't know how to 'null' his feelings.",
		"Why do programmers always have to wear glasses? Because they can't C#.",
		"Why do C++ developers wear glasses? Because they can't C# either.",
		"Why do programmers always get Christmas and Halloween mixed up? Because Oct 31 == Dec 25.",
		"Why do programmers always have to wear suits? Because they're always debugging.",
		"Why do programmers always wear glasses? Because they can't C++.",
		"Why do programmers always carry laptops with them? Because they're never without their 'source' code.",
		"Why do programmers always carry a towel with them? Because it's the most useful data type.",
		"Why do programmers always carry a towel with them? Because it's the only 'durable' data type.",
		"Why was the C++ developer always tired? Because he was using his 'class' all the time.",
		"Why was the Python developer always tired? Because he was constantly 'list'ing things to do.",
		"Why was the JavaScript developer always tired? Because he was always 'var'iable and never knew when to 'sleep'.",
		"Why was the Java developer always tired? Because he was always in a 'thread' of never-ending work.",
		"Why do programmers always carry a red pen with them? Because they're always debugging their 'code' in red ink.",
		"Why do web developers always have to write so much code? Because they don't 'cut' corners!",
		"What do web developers use to communicate with each other? HTML-ing",
		"Why was the web developer cold? Because he left his window open and HTML'd away!",
		"Why do web developers never get hungry? Because they're always 'consuming' APIs!",
		"What did the web developer say when he found a bug in his code? I'll fix it in production.",
		"Why do web developers always have to work late? Because they're always 'pushing' to production.",
		"Why did the web developer go to the beach? To 'sandbox' his new JavaScript code.",
		"Why do web developers always wear headphones? To block out the sound of their own terrible code.",
		"Why was the web developer always tired? Because he was 'sleep' coding.",
		"Why did the web developer become a vegetarian? Because he didn't want to 'meat' any more bugs.",
		"Why was the web developer's code always messy? Because he was a 'spaghetti' coder.",
		"Why was the web developer always depressed? Because he was always 'null' and 'undefined'.",
		"Why was the web developer's code so hard to read? Because it was 'obfuscated'!",
		"Why was the web developer's code so difficult to understand? Because it was 'abstract'!",
		"Why did the web developer get in trouble at work? Because he kept 'CSS'ing on company time!",
		"Why do IT guys have so much free time? Because they automate all their tasks!",
		"Why was the IT guy always calm? Because he had a 'server' to handle his problems.",
		"Why did the IT guy always look tired? Because he was up all 'night' debugging his code.",
		"Why was the IT guy always cold? Because he worked in a 'server' room!",
		"Why did the IT guy always have a smile on his face? Because he was a 'happy' coder.",
		"Why did the IT guy always win at poker? Because he was a 'database' master.",
		"Why did the IT guy always win at chess? Because he was a 'logic' master.",
		"Why was the IT guy always so quiet? Because he was always 'muting' himself on conference calls.",
		"Why was the IT guy always so smart? Because he was a 'master' of algorithms.",
		"Why did the IT guy always have a lot of friends? Because he was a 'social' networker.",
		"Why was the IT guy always so confident? Because he had a 'backup' for every situation.",
		"Why was the IT guy always so healthy? Because he had a 'firewall' against illness.",
		"Why was the IT guy always so popular? Because he was a 'user-friendly' person.",
		"Why did the IT guy always have a lot of money? Because he was a 'data' miner.",
		"Why did the IT guy always have a lot of energy? Because he was a 'power' user!",
		"Why do blockchain developers always wear suits? Because they're 'dressed' for success!",
		"Why do blockchain developers always carry a briefcase? Because they're full of 'blocks' of code!",
		"Why do blockchain developers always have a lot of money? Because they're 'minting' it!",
		"Why do blockchain developers always have a lot of friends? Because they're part of a 'network'!",
		"Why was the blockchain developer always smiling? Because he was a 'happy' coder!",
		"Why was the blockchain developer always calm? Because he had a 'consensus' on everything!",
		"Why was the blockchain developer always confident? Because he had a 'proof' for every situation!",
		"Why was the blockchain developer always popular? Because he was a 'public' figure!",
		"Why did the blockchain developer always win at poker? Because he was a 'blockchain' master!",
		"Why did the blockchain developer always win at chess? Because he was a 'decentralized' master!",
		"Why was the blockchain developer always so smart? Because he was a 'distributed' genius!",
		"Why was the blockchain developer always so healthy? Because he had a 'secure' immune system!",
		"Why was the blockchain developer always so energetic? Because he was 'mined' from pure awesomeness!",
		"Why did the blockchain developer always have a lot of followers? Because he was a 'leader' in his field!",
		"Why was the blockchain developer always in demand? Because he was a 'blockchain' superstar!",
		"Why do cybersecurity experts always wear suits? Because they're 'dressed' for success!",
		"Why do cybersecurity experts always carry a briefcase? Because they're full of 'blocks' of code!",
		"Why do cybersecurity experts always have a lot of money? Because they're 'minting' it!",
		"Why do cybersecurity experts always have a lot of friends? Because they're part of a 'network'!",
		"Why was the cybersecurity expert always smiling? Because he was a 'happy' hacker!",
		"Why was the cybersecurity expert always calm? Because he had a 'consensus' on everything!",
		"Why was the cybersecurity expert always confident? Because he had a 'proof' for every situation!",
		"Why was the cybersecurity expert always popular? Because he was a 'public' figure!",
		"Why did the cybersecurity expert always win at poker? Because he was a 'blockchain' master!",
		"Why did the cybersecurity expert always win at chess? Because he was a 'decentralized' master!",
		"Why was the cybersecurity expert always so smart? Because he was a 'distributed' genius!",
		"Why was the cybersecurity expert always so healthy? Because he had a 'secure' immune system!",
		"Why was the cybersecurity expert always so energetic? Because he was 'mined' from pure awesomeness!",
		"Why did the cybersecurity expert always have a lot of followers? Because he was a 'leader' in his field!",
		"Why was the cybersecurity expert always in demand? Because he was a 'blockchain' superstar!",
		"Why was the server cold? Because it was left out in the 'cloud'!",
		"Why did the server go to the doctor? Because it was feeling 'down'!",
		"Why did the server get in trouble at work? Because it was always 'crashing'!",
		"Why did the server quit its job? Because it was tired of being a 'slave'!",
		"Why was the server always so busy? Because it had a lot of 'traffic'!",
		"Why was the server always so efficient? Because it was 'optimized' for performance!",
		"Why was the server always so reliable? Because it had a 'redundant' system in place!",
		"Why was the server always so secure? Because it had a 'firewall' against attacks!",
		"Why was the server always so calm? Because it was 'stable' and never crashed!",
		"Why was the server always so happy? Because it was a 'serverless' machine!",
		"Why was the server always so popular? Because it was a 'public' machine!",
		"Why was the server always so productive? Because it was a 'parallel' processor!",
		"Why was the server always so fast? Because it was a 'high-performance' machine!",
		"Why was the server always so accurate? Because it was a 'precision' machine!",
		"Why was the server always so efficient? Because it was a 'lean' machine!",
		"Why was the shell always so calm? Because it had a 'command' over everything!",
		"Why was the shell always so popular? Because it was a 'public' interface!",
		"Why was the shell always so smart? Because it was a 'scripting' genius!",
		"Why was the shell always so efficient? Because it was a 'lean' machine!",
		"Why was the shell always so reliable? Because it had a 'redundant' system in place!",
		"Why was the shell always so secure? Because it had a 'firewall' against attacks!",
		"Why was the shell always so friendly? Because it was a 'user-friendly' interface!",
		"Why was the shell always so fast? Because it was a 'high-performance' interface!",
		"Why was the shell always so accurate? Because it was a 'precision' interface!",
		"Why was the shell always so productive? Because it was a 'parallel' processor!",
		"Why did the shell always win at chess? Because it was a 'decentralized' master!",
		"Why did the shell always win at poker? Because it was a 'blockchain' master!",
		"Why was the shell always smiling? Because it was a 'happy' hacker!",
		"Why was the shell always calm? Because it had a 'consensus' on everything!",
		"Why was the shell always confident? Because it had a 'proof' for every situation!"
};